version: '3'
services:
  solr:
    image: solr:9.4.0
    ports:
     - "8983:8983"
     - "8984:8984"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate 
      - data-catalogue
    healthcheck:
      test: "curl -f http://localhost:8983/solr"
      interval: 30s
      retries: 3
volumes:
  data:
