name: Issue
description: an issue with the data catalogue
title: issue title
labels: ["FAIRification", "Data Catalogue"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
 - id: references
   type: textarea
   attributes:
     label: References
     description: Name of reporter if external to the team, link to slack
