name: Issue
description: an issue with the data catalogue
title: issue title
body:
  - type: markdown
    attributes:
      value: |
        Describe your issue
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
